import Header from "@/components/Header";
import Footer from "@/components/Footer";
import './globals.css';
import NavMenu from "@/components/NavMenu";

export const metadata = {
  title: 'My Portfolio',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
  <html>
    <body className="bg-background">
      <Header NavMenu={<NavMenu />} />
      {children}
      <Footer />
    </body>
  </html>
 );
}
