import Header from "@/components/Header";
import Footer from "@/components/Footer";
import './globals.css';
import './parallax.css';
import NavMenu from "@/components/NavMenu";
import { Analytics } from "@vercel/analytics/react"

export const metadata = {
  title: 'Edward Montilla',
  description: 'Generated by Next.js',
}

// moved components to page.js

export default function RootLayout({ children }) {
 return (
  <html>
    <body>
      <Analytics />
      <Header NavMenu={<NavMenu />} />
      {children}
      {/* <Footer /> */}
    </body>
  </html>
 );
}
