import Header from "@/components/Header";
import Footer from "@/components/Footer";
import './globals.css';
import NavMenu from "@/components/NavMenu";

export const metadata = {
  title: 'Edward Montilla',
  description: 'Generated by Next.js',
}

// moved components to page.js

export default function RootLayout({ children }) {
 return (
  <html>
    <body>
      {/* <Header NavMenu={<NavMenu />} /> */}
      {children}
      {/* <Footer /> */}
    </body>
  </html>
 );
}
